<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace api\modules\v1\controllers;

use yii\rest\ActiveController;
// Json format
use yii\filters\ContentNegotiator;
use yii\web\Response;
use api\modules\v1\models\Post;

class PostController extends ActiveController {

    public $modelClass = 'api\modules\v1\models\Post';

    public function behaviors() {
        $behaviors = parent::behaviors();
        $behaviors['bootstrap'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        return $behaviors;
    }

    public function actions() {
        $actions = parent::actions();

        // will overriding return data on the index action
        // define this for custom search using the built in Search Class generated by Gii which is 
        // already performing validation and using 'like'
        // API: http://localhost/yii2-advanced-api/api/web/v1/posts?PostSearch[title]=rent
        $actions['index']['prepareDataProvider'] = [new Post(), 'prepareDataProvider'];

        // will overriding return data on the view action 
        unset($actions['view']);
        return $actions;
    }

    public function actionView($id) {

        if (isset($id)) {
            return Post::findOne($id);
        } else {
            throw new HttpException(404);
        }
    }

}
